version: "3.8"

services:
  postgres-backend:
    image: postgres:16
    container_name: postgres-backend
    environment:
      POSTGRES_DB: matricula_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-backend

  backend-matricula:
    build: .
    container_name: backend-matricula
    depends_on:
      - postgres-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-backend:5432/matricula_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: always
      SERVER_PORT: 8086
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8086:8086"
    restart: always

volumes:
  postgres_data:
